spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sice_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postdba}
spring.datasource.driver-class-name=org.postgresql.Driver

security.jwt.secret=${JWT_SECRET:Q3p2cGh1S3hKWE5mU2xWZE5vQXpwUXJ2UGFvRHJGd1g=}
security.jwt.expiration-seconds=3600