# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver

# security.jwt.secret=${JWT_SECRET}
# security.jwt.expiration-seconds=3600